homme(clement).
homme(thierry).
homme(claude).
homme(marcel).
homme(nicolas).
femme(julie).
femme(marie).
femme(severine).
femme(jeannine).
femme(maelis).
pere(marcel,thierry).
pere(marcel,claude).
pere(thierry,clement).
pere(thierry,julie).
pere(claude,nicolas).
pere(claude,maelis).
mere(jeannine,thierry).
mere(jeannine,claude).
mere(marie,clement).
mere(marie,julie).
mere(severine,nicolas).
mere(severine,maelis).
